inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'lib/generators/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 150
  Exclude:
    - 'config/routes.rb'
    - 'config/initializers/**'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact


Metrics/AbcSize:
  Max: 20
