version: "3.8"
services:
  web:
    build: .
    volumes:
      - .:/dual_focus:delegated
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    platform: linux/x86_64
